config_template/test_param_config_template.h
src/mqtt/mqtt_test.c

This PR made two changes to MQTT tests.
1. Fixed an issue with retained message test. Previously retained message test uses the same topic as other test. As a result MQTT_Subscribe_Publish_With_Qos_0 and MQTT_Subscribe_Publish_With_Qos_1 would receive a retained message when they subscribe to the topic, before the test cases make publishes. This PR fixed the issue by using a dedicated topic for retained message test.
2. Updated config template with MQTT credential options.

Mqtt Test Updates

---

src/common/thread_function.h
src/transport_interface/README.md
src/transport_interface/transport_interface_test.c
src/transport_interface/transport_interface_test.h

Update the transport interface test cases
* Update "SendRecvCompare" test case. Data size ranges from 1 - TRANSPORT_TEST_BUFFER_WRITABLE_LENGTH. The test case may take up to 10 minutes to complete the test. “...” log output to indicate the test is still running.
* Add Multithreaded test case, "SendRecvCompareMultithreaded". 
* Use test thread to detect transport interface blocking when no data to receive in “NoDataToReceive” and “ReturnZeroRetry” test cases.
* Makes invalid parameter tests optional.

Update transport interface test

---

src/mqtt/mqtt_test.c
src/transport_interface/transport_interface_test.c
tools/echo_server/README.md

This PR has the following changes:
1. Updated README in echo server about setting Common Name to server DNS.
2. Added param check in transport and MQTT test so that if server endpoint and port macros are not defined, the build will error out.

Param checking and documentation update

---

src/mqtt/mqtt_test.c
src/ota/ota_pal_test.c
src/pkcs11/core_pkcs11_test.c
src/transport_interface/transport_interface_test.c

Moved the X_TEST_ENABLED guards to cover the entire file. Previously the X_TEST_ENABLED guards only covers the run test functions. When building the project, users might see errors coming from tests that are not enabled. This PR makes all test source excluded from build unless the test is enabled.

Moved the X_TEST_ENABLED guards to cover the entire file

---

src/transport_interface/transport_interface_test.c

* Increase the retry loop count and test delay to total 10 seconds for
sendRecvCompare test case
* Add more check in test setup function
* Remove the usage of pTransport->pNetworkContext. Always use the
testParam.pNetworkContext.

Update transport interface test settings

---

src/mqtt/mqtt_test.c
src/ota/ota_pal_test.c
src/pkcs11/core_pkcs11_test.c
src/transport_interface/transport_interface_test.c

Moved test_execution_config.h to before test source guard. Otherwise the test source will still be excluded by preprocessor when test is enabled in test_execution_config.h.

Moved test_execution_config.h to before test source guard

---

src/pkcs11/core_pkcs11_test.c

* Remove the TEST_ASSERT_EQUAL_MESSAGE and TEST_ASSERT_NOT_EQUAL_MESSAGE in TEST_SETUP and TEST_TEAR_DOWN function. These functions abort the test directly if current test failed.
```C
TEST_TEAR_DOWN( Full_PKCS11_EC )
{
CK_RV xResult;
xResult = pxGlobalFunctionList->C_CloseSession( xGlobalSession );
/* The tear down function abort here if current test failed. The next C_Finalize is not called.
* The test cases design assume every test cases start with uninitialized PKCS11.
* The test case fails if the PKCS11 can't be initialized in the test setup function. */
TEST_ASSERT_EQUAL_MESSAGE( CKR_OK, xResult , "Failed to close session." ); /* Unity abort the test here. */
xResult = pxGlobalFunctionList->C_Finalize( NULL ); /*This function won't be called. */
TEST_ASSERT_EQUAL_MESSAGE( CKR_OK, …
```

Remove unity shorthand usage in pkcs11 test

---

src/mqtt/mqtt_test.c
src/ota/ota_pal_test.c
src/ota/ota_pal_test.h
src/pkcs11/core_pkcs11_test.c
src/transport_interface/transport_interface_test.c

This PR has the following updates in OTA PAL test:
1. Added configurable page size and OTA PAL test will make sure all writes are aligned with the provided page size.
2. Updated SetPlatformImageState related tests. otaPal_SetPlatformImageState_SelfTestImageState and otaPal_SetPlatformImageState_RejectImageState are removed because their setup is far from real world use and can cause some valid and reasonable OTA PAL implementation to fail the tests. otaPal_SetPlatformImageState_AcceptedStateWithoutClose is added to test otaPal_SetPlatformImageState fails correctly when it is called with otaImageAccepted state when it shouldn't be accepted.

Updated OTA PAL test

---

src/pkcs11/README.md

* Add PKCS#11 test README document

Add PKCS #11 test README document

---

src/pkcs11/core_pkcs11_test.c

* Fix variable might be clobbered by 'longjmp' warning
* Refine TEST_ABORT macro usage

Update pkcs11 test compile warning

---

src/transport_interface/transport_interface_test.c

* Remove TEST_ASSERT usage in multithread test to prevent setjmp and
longjump usage in thread function.
* Add network connection flag to prevent disconnect network connection which is not previously connected.

Update transport multithread test

---

config_template/test_param_config_template.h
src/common/platform_function.h
src/mqtt/mqtt_test.c
src/mqtt/mqtt_test.h

Patches includes:
1. Move rand() related function to platform header file
- FRTest_GenerateRandInt
2. Add MqttTestGetTimeMs to MqttTestParam_t in mqtt_test.h
- Used for MQTT_Init. Customers need to provide this function.

MQTT Test: Add FRTest_GenerateRandInt and MqttTestGetTimeMs.

---

src/common/platform_function.h
src/mqtt/mqtt_test.c

This PR updates the tests so that they can work with the API changes in coreMQTT `v2.0.0`.

Update tests to match the latest changes in coreMQTT library

---

src/ota/ota_pal_test.c

Fix OTA PAL Test compilation for LTS 2.0 libraries
- Replace Sig256_t with Sig_t for [OTA commit](https://github.com/aws/ota-for-aws-iot-embedded-sdk/commit/6ccb758fb9da5fe5da965036c3af96c7329cc453).

OTA PAL Test: Replace Sig256_t with Sig_t for LTS 2.0 udpate.

---

src/mqtt/mqtt_test.c

Fix MQTT test case: 
- Check incomingInfo by length to avoid accessing NULL pointer.

Check incomingInfo by length to avoid accessing NULL pointer.

---

src/mqtt/mqtt_test.c

This PR adds a test which subscribes to multiple topics and unsubscribes from multiple topics in single call to `MQTT_Subscribe` and `MQTT_Unsubscribe` APIs.

Add Subscribe and Unsubscribe test

---

config_template/test_param_config_template.h
src/mqtt/mqtt_test.c

Add process loop timeout configuration and check received topic in MQTT test.

Add process loop timeout configuration and check received topic in MQTT test.

---

src/mqtt/mqtt_test.c

Remove configPirntf in mqtt_test.c.
There is no configPrintf in GRI iot-reference-stm32u5. It is a platform dependent function.

Remove configPirntf in mqtt_test.c

---

version-mappings.yml

I have updated the old P3 release version number from `202210.00` to `202211.00`, this change depends on the repo being tagged with `202210.01`. IDT looks at the `version-mappings.yml` file based on the release tag of the repo, and checks for the FreeRTOS version. Since 202211.00 is not associated with `202210.00` tests repo tag, we need a new tag.

Update to include P3 release, 202211.00, and new FreeRTOS-Libraries-Integration-Tests release tag

---

src/mqtt/mqtt_test.c

Fail log like this
./components/FreeRTOS-Libraries-Integration-Tests/FreeRTOS-Libraries-Integration-Tests/src/mqtt/mqtt_test.c:1616::FAIL: This test leaks!

Free MQTT topic name and payload in multiple sub/unsub test

---

version-mappings.yml

Add new FreeRTOS version 202212.01 to version mappings file for IDT.

Add FRv202212.01 to version mappings

---

tools/echo_server/README.md
tools/echo_server/config.json
tools/echo_server/echo_server.go

Add support for UDP echo server

Add support for UDP echo server

---

src/pkcs11/README.md
src/pkcs11/core_pkcs11_test.c
src/pkcs11/dev_mode_key_provisioning/dev_mode_key_provisioning.c
src/pkcs11/rsa_test_credentials.h

The tested platform may already be pre-provisioned with keys other than those provided in the test. The PKCS11_RSA_GetAttributeValue test may fail to verify the RSA pre-provisioning mechanism under this scenario.
In this PR:
* Add `PKCS11_TEST_RSA_CERTIFICATE` and `PKCS11_TEST_RSA_CERTIFICATE_TEST` for platform with preprovisioned RSA key.
* Since the preprovisioned certificate is also provided int the test through these two macros. We can also verify the certificate acquired through pkcs11 API is the same as the certificate pre-provisioned now. The condition to check provision method is removed.
-----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Fix RSA PKCS11_RSA_GetAttributeValue test

---

src/mqtt/mqtt_test.c

*Issue #, if available:*
*Description of changes:*
`MQTT_KEEP_ALIVE_INTERVAL_SECONDS` macro value depends on the responsiveness of the target running the tests because some targets might be faster or slower than others. Hence, it would be useful to have a default value for this macro (5) and the integration code can provide other value if needed.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Introduce user defined MQTT keep alive value
